services:
  db:
    container_name: allyend-db
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-allyend}
      - POSTGRES_USER=${POSTGRES_USER:-allyend}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-allyend}
    volumes:
      - ${DOCKER_DB_DIR:-./data/pgdata}:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-allyend} -d ${POSTGRES_DB:-allyend}"]
      interval: 5s
      timeout: 3s
      retries: 10
    restart: unless-stopped

  backend:
    container_name: allyend-backend
    build:
      context: .
      dockerfile: Dockerfile.backend
    image: allyend/backend:latest
    env_file:
      - ./.env
    environment:
      - PORT=${PORT:-9093}
    volumes:
      - ${DOCKER_DATA_DIR:-./data}:/app/data # 数据库与上传文件目录
      - ${DOCKER_LOG_DIR:-./logs}:/app/logs  # 应用日志目录
    expose:
      - "${PORT:-9093}"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  frontend:
    container_name: allyend-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL:-/api}
        NEXT_PUBLIC_APP_BASE_URL: ${NEXT_PUBLIC_APP_BASE_URL:-http://localhost:8080}
        BACKEND_ORIGIN: ${BACKEND_ORIGIN:-http://allyend-backend:9093}
    image: allyend/frontend:latest
    environment:
      NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL:-/api}
      NEXT_PUBLIC_APP_BASE_URL: ${NEXT_PUBLIC_APP_BASE_URL:-http://localhost:8080}
      BACKEND_ORIGIN: ${BACKEND_ORIGIN:-http://allyend-backend:9093}
    expose:
      - "3000"
    depends_on:
      - backend
    restart: unless-stopped

  reverse-proxy:
    container_name: allyend-proxy
    image: nginx:1.27-alpine
    depends_on:
      - backend
      - frontend
    volumes:
      - ./deploy/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "${DOCKER_PROXY_PORT:-8080}:80"
    restart: unless-stopped
