export const endpoints = {
  auth: {
    login: "/api/auth/login",
    register: "/api/auth/register",
    profile: "/api/users/me",
    logout: "/api/auth/logout",
    sessions: "/api/auth/sessions",
    sessionById: (id: string) => `/api/auth/sessions/${id}`,
    avatar: "/api/users/me/avatar",
  },
  files: {
    listMine: "/files/me",
    uploadMine: "/files/me/up",
    deleteFile: (id: number | string) => `/files/me/${id}`,
    updateFile: (id: number | string) => `/files/me/${id}`,
    downloadFile: (id: number | string) => `/files/${id}/download`,
    tokens: "/files/tokens",
    tokenById: (id: number | string) => `/files/tokens/${id}`,
    logs: "/files/api/logs",
  },
  crawlers: {
    list: `/pa/api/me`,
    register: `/pa/api/register`,
    detail: (id: number | string) => `/pa/api/me/${id}`,
    runs: (id: number | string) => `/pa/api/me/${id}/runs`,
    logs: (id: number | string) => `/pa/api/me/${id}/logs`,
    heartbeats: (id: number | string) => `/pa/api/me/${id}/heartbeats`,
    commands: {
      list: (id: number | string) => `/pa/api/me/${id}/commands`,
      create: (id: number | string) => `/pa/api/me/${id}/commands`,
      ack: (crawlerId: number | string, commandId: number | string) => `/pa/api/${crawlerId}/commands/${commandId}/ack`,
      fetch: (id: number | string) => `/pa/api/${id}/commands/next`,
    },
    groups: {
      list: `/pa/api/groups`,
      byId: (id: number | string) => `/pa/api/groups/${id}`,
    },
    config: {
      templates: {
        list: `/pa/api/config/templates`,
        create: `/pa/api/config/templates`,
        byId: (id: number | string) => `/pa/api/config/templates/${id}`,
      },
      assignments: {
        list: `/pa/api/config/assignments`,
        create: `/pa/api/config/assignments`,
        byId: (id: number | string) => `/pa/api/config/assignments/${id}`,
      },
      fetch: (id: number | string) => `/pa/api/${id}/config`,
    },
    alerts: {
      rules: {
        list: `/pa/api/alerts/rules`,
        create: `/pa/api/alerts/rules`,
        byId: (id: number | string) => `/pa/api/alerts/rules/${id}`,
      },
      events: `/pa/api/alerts/events`,
    },
    quickLinks: {
      list: `/pa/api/links`,
      byId: (id: number | string) => `/pa/api/links/${id}`,
    },
  },
  apiKeys: {
    list: `/api/keys`,
    create: `/api/keys`,
    update: (id: number | string) => `/api/keys/${id}`,
    delete: (id: number | string) => `/api/keys/${id}`,
    rotate: (id: number | string) => `/api/keys/${id}/rotate`,
    public: `/api/public/keys`,
  },
  admin: {
    users: "/hjxgl/api/users",
    userById: (id: number | string) => `/hjxgl/api/users/${id}`,
    invites: "/hjxgl/api/invites",
    inviteById: (id: number | string) => `/hjxgl/api/invites/${id}`,
    groups: "/hjxgl/api/groups",
    settings: "/hjxgl/api/settings",
    registration: "/hjxgl/api/settings/registration",
  },
  dashboard: {
    overview: "/api/dashboard/overview",
    theme: "/api/users/me/theme",
    recentActivity: "/api/dashboard/activity",
    public: "/public",
  },
};
